# Generated by Django 4.1.1 on 2022-09-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boleta',
            name='rut',
            field=models.CharField(max_length=20),
        ),
    ]
