# Generated by Django 4.1.1 on 2022-10-23 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_boleta_rut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='num_sucursal',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='numero_cliente',
        ),
    ]
