# Generated by Django 4.1.1 on 2022-10-31 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_boleta_monto_remove_sucursal_num_sucursal_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='tipo_consumo',
            new_name='tipo_servicio',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='rut',
        ),
    ]
