# Generated by Django 4.1.1 on 2022-11-01 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_rename_tipo_consumo_boleta_tipo_servicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boleta',
        ),
    ]
