# Generated by Django 4.1.1 on 2022-11-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_boleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='numero_cliente',
            field=models.CharField(default=15, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boleta',
            name='rut_emisor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='rut_receptor',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='boleta',
            name='tipo_servicio',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='correo',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='comuna',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='distribuidor',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='formato',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre_unidad',
            field=models.CharField(max_length=40),
        ),
    ]
