# Generated by Django 4.1.1 on 2022-11-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_sucursal_numero_cliente_alter_boleta_rut_emisor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='anio_doc',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='dia_doc',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='folio',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boleta',
            name='mes_doc',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sucursal',
            name='num_sucursal',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
