# Generated by Django 4.1.1 on 2022-11-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_alter_boleta_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='comentario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
