# Generated by Django 4.1.1 on 2022-11-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_sucursal_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='comentario',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
