-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.auth_user
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT auth_user_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.auth_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.auth_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_clockedschedule
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    clocked_time timestamp with time zone NOT NULL,
    CONSTRAINT django_celery_beat_clockedschedule_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_crontabschedule
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    minute character varying(240) COLLATE pg_catalog."default" NOT NULL,
    hour character varying(96) COLLATE pg_catalog."default" NOT NULL,
    day_of_week character varying(64) COLLATE pg_catalog."default" NOT NULL,
    day_of_month character varying(124) COLLATE pg_catalog."default" NOT NULL,
    month_of_year character varying(64) COLLATE pg_catalog."default" NOT NULL,
    timezone character varying(63) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_celery_beat_crontabschedule_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_intervalschedule
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    every integer NOT NULL,
    period character varying(24) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_celery_beat_intervalschedule_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_periodictask
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    task character varying(200) COLLATE pg_catalog."default" NOT NULL,
    args text COLLATE pg_catalog."default" NOT NULL,
    kwargs text COLLATE pg_catalog."default" NOT NULL,
    queue character varying(200) COLLATE pg_catalog."default",
    exchange character varying(200) COLLATE pg_catalog."default",
    routing_key character varying(200) COLLATE pg_catalog."default",
    expires timestamp with time zone,
    enabled boolean NOT NULL,
    last_run_at timestamp with time zone,
    total_run_count integer NOT NULL,
    date_changed timestamp with time zone NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    crontab_id integer,
    interval_id integer,
    solar_id integer,
    one_off boolean NOT NULL,
    start_time timestamp with time zone,
    priority integer,
    headers text COLLATE pg_catalog."default" NOT NULL,
    clocked_id integer,
    expire_seconds integer,
    CONSTRAINT django_celery_beat_periodictask_pkey PRIMARY KEY (id),
    CONSTRAINT django_celery_beat_periodictask_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_periodictasks
(
    ident smallint NOT NULL,
    last_update timestamp with time zone NOT NULL,
    CONSTRAINT django_celery_beat_periodictasks_pkey PRIMARY KEY (ident)
);

CREATE TABLE IF NOT EXISTS public.django_celery_beat_solarschedule
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    event character varying(24) COLLATE pg_catalog."default" NOT NULL,
    latitude numeric(9, 6) NOT NULL,
    longitude numeric(9, 6) NOT NULL,
    CONSTRAINT django_celery_beat_solarschedule_pkey PRIMARY KEY (id),
    CONSTRAINT django_celery_beat_solar_event_latitude_longitude_ba64999a_uniq UNIQUE (event, latitude, longitude)
);

CREATE TABLE IF NOT EXISTS public.django_celery_results_chordcounter
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    group_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    sub_tasks text COLLATE pg_catalog."default" NOT NULL,
    count integer NOT NULL,
    CONSTRAINT django_celery_results_chordcounter_pkey PRIMARY KEY (id),
    CONSTRAINT django_celery_results_chordcounter_group_id_key UNIQUE (group_id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_results_groupresult
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    group_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    date_created timestamp with time zone NOT NULL,
    date_done timestamp with time zone NOT NULL,
    content_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    content_encoding character varying(64) COLLATE pg_catalog."default" NOT NULL,
    result text COLLATE pg_catalog."default",
    CONSTRAINT django_celery_results_groupresult_pkey PRIMARY KEY (id),
    CONSTRAINT django_celery_results_groupresult_group_id_key UNIQUE (group_id)
);

CREATE TABLE IF NOT EXISTS public.django_celery_results_taskresult
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    task_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    status character varying(50) COLLATE pg_catalog."default" NOT NULL,
    content_type character varying(128) COLLATE pg_catalog."default" NOT NULL,
    content_encoding character varying(64) COLLATE pg_catalog."default" NOT NULL,
    result text COLLATE pg_catalog."default",
    date_done timestamp with time zone NOT NULL,
    traceback text COLLATE pg_catalog."default",
    meta text COLLATE pg_catalog."default",
    task_args text COLLATE pg_catalog."default",
    task_kwargs text COLLATE pg_catalog."default",
    task_name character varying(255) COLLATE pg_catalog."default",
    worker character varying(100) COLLATE pg_catalog."default",
    date_created timestamp with time zone NOT NULL,
    periodic_task_name character varying(255) COLLATE pg_catalog."default",
    CONSTRAINT django_celery_results_taskresult_pkey PRIMARY KEY (id),
    CONSTRAINT django_celery_results_taskresult_task_id_key UNIQUE (task_id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_cron_cronjoblock
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    job_name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    locked boolean NOT NULL,
    CONSTRAINT django_cron_cronjoblock_pkey PRIMARY KEY (id),
    CONSTRAINT django_cron_cronjoblock_job_name_key UNIQUE (job_name)
);

CREATE TABLE IF NOT EXISTS public.django_cron_cronjoblog
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    code character varying(64) COLLATE pg_catalog."default" NOT NULL,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    is_success boolean NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    ran_at_time time without time zone,
    CONSTRAINT django_cron_cronjoblog_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.web_boleta
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    rut_emisor character varying(10) COLLATE pg_catalog."default" NOT NULL,
    rut_receptor character varying(10) COLLATE pg_catalog."default" NOT NULL,
    tipo_servicio character varying(3) COLLATE pg_catalog."default" NOT NULL,
    anio_doc integer NOT NULL,
    dia_doc integer NOT NULL,
    folio integer NOT NULL,
    mes_doc integer NOT NULL,
    comentario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT web_boleta_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.web_cliente
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    nombre character varying(35) COLLATE pg_catalog."default" NOT NULL,
    rut character varying(10) COLLATE pg_catalog."default" NOT NULL,
    "contraseña" character varying(20) COLLATE pg_catalog."default" NOT NULL,
    correo character varying(70) COLLATE pg_catalog."default" NOT NULL,
    comentario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT web_usuarios_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.web_sucursal
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    codigo character varying(10) COLLATE pg_catalog."default" NOT NULL,
    nombre_unidad character varying(40) COLLATE pg_catalog."default" NOT NULL,
    estado character varying(20) COLLATE pg_catalog."default" NOT NULL,
    direccion character varying(60) COLLATE pg_catalog."default" NOT NULL,
    comuna character varying(25) COLLATE pg_catalog."default" NOT NULL,
    region character varying(4) COLLATE pg_catalog."default" NOT NULL,
    zona character varying(10) COLLATE pg_catalog."default" NOT NULL,
    distribuidor character varying(25) COLLATE pg_catalog."default" NOT NULL,
    formato character varying(11) COLLATE pg_catalog."default" NOT NULL,
    numero_cliente character varying(15) COLLATE pg_catalog."default" NOT NULL,
    num_sucursal integer NOT NULL,
    comentario character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT web_sucursal_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_group_id_97559544
    ON public.auth_user_groups(group_id);


ALTER TABLE IF EXISTS public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_groups_user_id_6a12ed8b
    ON public.auth_user_groups(user_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_permission_id_1fbb5f2c
    ON public.auth_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_user_user_permissions_user_id_a95ead1b
    ON public.auth_user_user_permissions(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id)
    REFERENCES public.auth_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_clocked_id_47a69f82_fk_django_ce FOREIGN KEY (clocked_id)
    REFERENCES public.django_celery_beat_clockedschedule (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_celery_beat_periodictask_clocked_id_47a69f82
    ON public.django_celery_beat_periodictask(clocked_id);


ALTER TABLE IF EXISTS public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_crontab_id_d3cba168_fk_django_ce FOREIGN KEY (crontab_id)
    REFERENCES public.django_celery_beat_crontabschedule (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_celery_beat_periodictask_crontab_id_d3cba168
    ON public.django_celery_beat_periodictask(crontab_id);


ALTER TABLE IF EXISTS public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_interval_id_a8ca27da_fk_django_ce FOREIGN KEY (interval_id)
    REFERENCES public.django_celery_beat_intervalschedule (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_celery_beat_periodictask_interval_id_a8ca27da
    ON public.django_celery_beat_periodictask(interval_id);


ALTER TABLE IF EXISTS public.django_celery_beat_periodictask
    ADD CONSTRAINT django_celery_beat_p_solar_id_a87ce72c_fk_django_ce FOREIGN KEY (solar_id)
    REFERENCES public.django_celery_beat_solarschedule (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_celery_beat_periodictask_solar_id_a87ce72c
    ON public.django_celery_beat_periodictask(solar_id);

END;