# Generated by Django 4.1.1 on 2022-09-09 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Cliente',
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('monto', models.IntegerField(max_length=200)),
                ('tipo_consumo', models.CharField(max_length=30)),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.cliente')),
            ],
        ),
    ]
