# Generated by Django 4.1.1 on 2022-09-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_rename_usuarios_cliente_boleta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_sucursal', models.IntegerField(max_length=4)),
                ('codigo', models.CharField(max_length=10)),
                ('nombre_unidad', models.CharField(max_length=70)),
                ('numero_cliente', models.IntegerField(max_length=15)),
                ('estado', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=100)),
                ('comuna', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=4)),
                ('zona', models.CharField(max_length=10)),
                ('distribuidor', models.CharField(max_length=30)),
                ('formato', models.CharField(max_length=20)),
            ],
        ),
    ]
